name = "stage_1"
# movement types
# parabolic -- arc in/out
# explore -- moves around entire screen
# static -- hovers in place
# retreat -- runs away
# dive -- kamakaze dive at player position

# enemy types
# whitebird -- threat: low
# blackbird -- threat: low
# spacestation -- threat: low
# sprinkler -- threat: med

[[enemies]]
timestamp = 1
[[enemies.types]]
delay = 800
enter = 'left'
movement = ['parabolic']
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = ['parabolic']
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = ['parabolic']
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = ['parabolic']
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = ['parabolic']
type = "whitebird"

[[enemies]]
timestamp = 6
[[enemies.types]]
delay = 800
enter = 'right'
movement = ['parabolic']
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = ['parabolic']
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = ['parabolic']
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = ['parabolic']
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = ['parabolic']
type = "blackbird"

[[enemies]]
timestamp = 12
[[enemies.types]]
delay = 0
enter = 'center'
movement = ['explore']
type = "spacestation"

[[enemies]]
timestamp = 18
[[enemies.types]]
delay = 200
enter = 'center'
movement = ['explore']
type = "spacestation"
[[enemies.types]]
delay = 200
enter = 'left'
movement = ['parabolic']
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = ['parabolic']
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = ['parabolic']
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = ['parabolic']
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = ['parabolic']
type = "whitebird"

[[enemies]]
timestamp = 22
[[enemies.types]]
delay = 200
enter = 'right'
movement = ['dive']
type = "blackbird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = ['dive']
type = "blackbird"
[[enemies.types]]
delay = 200
enter = 'right'
movement = ['dive']
type = "blackbird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = ['dive']
type = "blackbird"
