name = "stage_1"
# movement types
# parabolic -- arc in/out
# explore -- moves around entire screen
# static -- hovers in place
# retreat -- runs away
# charge -- kamakaze charge at player position

# enemy types
# whitebird -- threat: low
# blackbird -- threat: low
# spacestation -- threat: low
# sprinkler -- threat: med

[[enemies]]
timestamp = 10
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"

[[enemies]]
timestamp = 16
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"

[[enemies]]
timestamp = 22
[[enemies.types]]
delay = 0
enter = 'center'
movement = 'explore'
type = "itemGiver"

[[enemies]]
timestamp = 28
[[enemies.types]]
delay = 200
enter = 'center'
movement = 'explore'
type = "itemGiver"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"

[[enemies]]
timestamp = 32
[[enemies.types]]
delay = 200
enter = 'right'
movement = 'charge'
type = "blackbird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'charge'
type = "blackbird"
[[enemies.types]]
delay = 200
enter = 'right'
movement = 'charge'
type = "blackbird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'charge'
type = "blackbird"

[[enemies]]
timestamp = 40
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"

[[enemies]]
timestamp = 46
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"

[[enemies]]
timestamp = 52
[[enemies.types]]
delay = 0
enter = 'center'
movement = 'explore'
type = "itemGiver"

[[enemies]]
timestamp = 58
[[enemies.types]]
delay = 200
enter = 'center'
movement = 'explore'
type = "itemGiver"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"

[[enemies]]
timestamp = 62
[[enemies.types]]
delay = 200
enter = 'right'
movement = 'charge'
type = "blackbird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'charge'
type = "blackbird"
[[enemies.types]]
delay = 200
enter = 'right'
movement = 'charge'
type = "blackbird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'charge'
type = "blackbird"

[[enemies]]
timestamp = 65
[[enemies.types]]
delay = 0
enter = 'center'
movement = 'hover'
type = "spacestation"

[[enemies]]
timestamp = 70
[[enemies.types]]
delay = 0
enter = 'center'
movement = 'explore'
type = "itemGiver"

[[enemies]]
timestamp = 75
[[enemies.types]]
delay = 0
enter = 'center'
movement = 'hover'
type = "spacestation"

[[enemies]]
timestamp = 75
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"

[[enemies]]
timestamp = 80
[[enemies.types]]
delay = 0
enter = 'center'
movement = 'hover'
type = "spacestation"

[[enemies]]
timestamp = 80
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
