name = "stage_1"
# movement types
# parabolic -- arc in/out
# explore -- moves around entire screen
# static -- hovers in place
# retreat -- runs away
# charge -- kamakaze charge at player position

# enemy types
# whitebird -- threat: low
# blackbird -- threat: low
# spacestation -- threat: low
# sprinkler -- threat: med

[[enemies]]
timestamp = 12
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
x = 300
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
x = 600
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
x = 300
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
x = 600
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
x = 300


[[enemies]]
timestamp = 16
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"

[[enemies]]
timestamp = 18
[[enemies.types]]
delay = 0
enter = 'right'
movement = 'explore'
type = "vendor"

[[enemies]]
timestamp = 22
[[enemies.types]]
delay = 0
enter = 'left'
movement = 'explore'
type = "vendor"

[[enemies]]
timestamp = 24
[[enemies.types]]
delay = 200
enter = 'position'
movement = 'charge'
type = "blackbird"
x = 250
[[enemies.types]]
delay = 200
enter = 'position'
movement = 'charge'
type = "blackbird"
x = 300
[[enemies.types]]
delay = 200
enter = 'position'
movement = 'charge'
type = "blackbird"
x = 350
[[enemies.types]]
delay = 200
enter = 'position'
movement = 'charge'
type = "blackbird"
x = 400

[[enemies]]
timestamp = 28
[[enemies.types]]
delay = 200
enter = 'center'
movement = 'explore'
type = "vendor"

[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"

[[enemies]]
timestamp = 32
[[enemies.types]]
delay = 200
enter = 'position'
movement = 'charge'
type = "blackbird"
x = 250
[[enemies.types]]
delay = 200
enter = 'position'
movement = 'charge'
type = "blackbird"
x = 300
[[enemies.types]]
delay = 200
enter = 'position'
movement = 'charge'
type = "blackbird"
x = 350
[[enemies.types]]
delay = 200
enter = 'position'
movement = 'charge'
type = "blackbird"
x = 400

[[enemies]]
timestamp = 38
[[enemies.types]]
delay = 200
enter = 'position'
movement = 'charge'
type = "blackbird"
x = 500
[[enemies.types]]
delay = 200
enter = 'position'
movement = 'charge'
type = "blackbird"
x = 450
[[enemies.types]]
delay = 200
enter = 'position'
movement = 'charge'
type = "blackbird"
x = 400
[[enemies.types]]
delay = 200
enter = 'position'
movement = 'charge'
type = "blackbird"
x = 350

[[enemies]]
timestamp = 40
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 800
enter = 'left'
movement = 'parabolic'
type = "whitebird"

[[enemies]]
timestamp = 46
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"
[[enemies.types]]
delay = 800
enter = 'right'
movement = 'parabolic'
type = "blackbird"

[[enemies]]
timestamp = 52
[[enemies.types]]
delay = 0
enter = 'center'
movement = 'explore'
type = "vendor"

[[enemies]]
timestamp = 58
[[enemies.types]]
delay = 200
enter = 'center'
movement = 'explore'
type = "vendor"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'parabolic'
type = "whitebird"

[[enemies]]
timestamp = 62
[[enemies.types]]
delay = 200
enter = 'right'
movement = 'charge'
type = "blackbird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'charge'
type = "blackbird"
[[enemies.types]]
delay = 200
enter = 'right'
movement = 'charge'
type = "blackbird"
[[enemies.types]]
delay = 200
enter = 'left'
movement = 'charge'
type = "blackbird"

[[enemies]]
timestamp = 65
[[enemies.types]]
delay = 0
enter = 'center'
movement = 'hover'
type = "spacestation"

[[enemies]]
timestamp = 70
[[enemies.types]]
delay = 0
enter = 'center'
movement = 'explore'
type = "vendor"

[[enemies]]
timestamp = 75
[[enemies.types]]
delay = 0
enter = 'center'
movement = 'hover'
type = "spacestation"

[[enemies]]
timestamp = 75
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"

[[enemies]]
timestamp = 80
[[enemies.types]]
delay = 0
enter = 'center'
movement = 'hover'
type = "spacestation"

[[enemies]]
timestamp = 80
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
[[enemies.types]]
delay = 100
enter = 'random'
movement = 'kamakaze'
type = "spear"
