name = "classes"

[generalClassInfo]
name = "Virtual Harp Classes"
term = "Spring Term 2021"
start = "April 13th"
end = "May 18th"
where = "Virtually on Zoom"
duration = "1 hr/week (6weeks)"
fee = "$175"

# ===============================

[[session]]
order = 1
name = "Intermediate"
when = "Tuesdays, 5:00pm - 6:00pm"
description = "For students who have either been through my beginner course (and know the first two Welsh tunes), or anyone with a working knowledge of the harp, and knows how to play a few pieces (or more) with both hands."

[[session.repretoire]]
name = "Princess Augusta (Scottish)"

[[session.repretoire]]
name = "Blind John the Harper (Welsh)"

[[session.repretoire]]
name = "Planxty Irwin (Irish, O’Carolan)"

[[session.repretoire]]
name = "Nora Criona (Irish Jig)"

# ===============================

[[session]]
order = 2
name = "Advanced"
when = "Tuesdays, 6:15pm - 7:15pm"
description = "For students with more extensive experience, this class will basically be a continuation of the Winter Term class, but open to all advanced players."

[[session.repretoire]]
name = "Planxty Crowell"

[[session.repretoire]]
name = "Carolan's Reciept"

# ===============================

[[session]]
order = 3
name = "Beginner II"
when = "Tuesdays, 7:30pm - 9:00pm"
description = "For students who are either continuing from the last Winter term and want some review plus more; or those who are starting for the first time but have had a good intro from me – we’ll warm up with fingering exercises, scales and arpeggios, review the first two Welsh harp tunes, (which gives you all the fundamentals of harp playing) and add more to your repertoire."

[[session.repretoire]]
name = "More Welsh Tunes"

[[session.repretoire]]
name = "Song of the Chanter"

[[session.repretoire]]
name = "Brian Boru's March"

[[session.repretoire]]
name = "Ye Wild Morris Dance"
