name = "events"

[[eventData]]
key = "threeRivers"
title = "Three Rivers Virtual Holiday Homebound Concert"
description = "Featuring Curtis and Loretta Heidi Muller and Bob Webb Magical Strings and Watch the Sky."

[[eventData.performances]]
date = "12/5/2020"
time = "6:00pm PST"
venue = "Vimeo"
callToAction = "Stream Online"
ticketLink = "https =//vimeo.com/479388039"
location = "Online Stream"
googleMaps = ""
ticketInfo = "Donations appreciated for viewing this concert."

# ===============================

[[eventData]]
key = "yuletide"
title = "42nd Annual Celtic Yuletide Celebration"
description = "For many in the Northwest it wouldn’t be the holidays without the harps dulcimers and energetic Celtic sounds of acclaimed family ensemble Magical Strings. The tradition continues this year as Magical Strings announces its 42nd year of annual Celtic Yuletide Concerts taking place virtually throughout Puget Sound in December 2020! The Boulding Family’s musical celebration of the holiday season is a treasured tradition – one that will continue despite the limitations of the global pandemic. While we can’t come together in person with each other and the Boulding family this year please join us online to celebrate the season. As always Pam and Philip Boulding will be joined by their children grandchildren and select guests for an afternoon of enchanting Yuletide music. The Boulding’s perform on Celtic harps hammered dulcimers strings and percussion while grandchildren from the Tara Academy add Irish step dancing for a festive and memorable performance. This year we are all experiencing dramatic changes to cherished traditions and that certainly includes the Celtic Yuletide Concerts with 42 years of performing together as a family all over the Northwest.Thank you for supporting Magical Strings purchasing tickets and joining us for this unusual virtual celebration. We wish you a peaceful and heart-warming holiday and Christmas season. May this concert help to bring us closer together even though we all must stay safe and physically isolated from one another. Together we can continue to kindle the light of Yuletide!"

[[eventData.performances]]
date = "12/6/2020"
time = "3:00pm"
venue = "Kent Spotlight Series (Online)"
callToAction = "Buy Tickets"
ticketLink = "https =//www.kentwa.gov/residents/parks-recreation-and-community-services/arts/spotlight-series-2019-2020"
location = "Kent"
googleMaps = ""
ticketInfo = "Not available after 12/6."

[[eventData.performances]]
date = "12/13/2020"
time = "3:00pm"
venue = "Lincoln Theatre (Online)"
callToAction = "Buy Tickets"
ticketLink = "https =//lincolntheatre.org/film/magical-strings-celtic-yuletide-virtual-concert"
location = "Mt. Vernon"
googleMaps = ""
ticketInfo = "Ticket sales support Magical Strings and the venue."

[[eventData.performances]]
date = "12/16/2020"
time = "7:00pm"
venue = "Alberta Rose Theatre (Online)"
callToAction = "Buy Tickets"
ticketLink = "https =//albertarosetheatre.com/events/magical-strings-presents-celtic-yuletide-on-the-portland-music-stream/"
location = "Portland"
googleMaps = ""
ticketInfo = "Ticket sales support Magical Strings and the venue."
