name = "spacestation"

# default attributes
contain = true
enter = "random"
hp = 3000
item = false
movement = "hover"
movementSpeed = 2
pointValue = 1000
spin = true
tracking = false
weaponDelay = 2000
weaponSpeed = 4
weaponType = "spincycle"
x = 250
y = 0
