name = "spacestation"

# default attributes
contain = true
enter = "random"
hp = 100
item = true
movement = "parabolic"
movementSpeed = 2
spin = true
tracking = true
weaponDelay = 2000
weaponSpeed = 6
weaponType = "ball"
